<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Checkout_icon_bag_alt</name>
   <tag></tag>
   <elementGuidId>2ed60832-ff90-4254-8c28-ca2b2cfe3024</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='nav-menu-item-cart']/a/span/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.icon_bag_alt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>9cd8093a-a117-4dba-b888-e5b9682ab8da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon_bag_alt</value>
      <webElementGuid>4e66675f-10d5-424f-8b9c-646ee8d7c9a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-menu-item-cart&quot;)/a[@class=&quot;cart-button&quot;]/span[@class=&quot;cart-item has-items&quot;]/i[@class=&quot;icon_bag_alt&quot;]</value>
      <webElementGuid>c8d6d89d-d617-4663-a72c-413537e823ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>ec1d2cf7-d8f8-4f52-900c-5879e77a60fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon_bag_alt</value>
      <webElementGuid>907e5679-09aa-4918-baae-937760728e04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-menu-item-cart&quot;)/a[@class=&quot;cart-button&quot;]/span[@class=&quot;cart-item has-items&quot;]/i[@class=&quot;icon_bag_alt&quot;]</value>
      <webElementGuid>fa8c438a-d251-4576-afe9-68e5e065b6f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='nav-menu-item-cart']/a/span/i</value>
      <webElementGuid>615aba7d-1f1d-434d-9217-b1dc3e20947a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/i</value>
      <webElementGuid>f934c19e-d3d3-4532-95e1-43e1036e958f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
