<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Choose an optionLargeMediumSmall</name>
   <tag></tag>
   <elementGuidId>56c53d48-8782-42c6-8da2-f99e01611334</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='pa_size']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pa_size</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>23401e2e-ec4e-4384-9a36-a1ea65e79b40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pa_size</value>
      <webElementGuid>a343dcdd-8f4d-4bc3-a5f3-80a7087940d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>attribute_pa_size</value>
      <webElementGuid>2eed0b84-0d1c-4883-97c2-fd2024049dae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-attribute_name</name>
      <type>Main</type>
      <value>attribute_pa_size</value>
      <webElementGuid>96492ee6-cbc4-43f1-b1b6-4cbe7b7ab5d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-show_option_none</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>86cf5a11-e416-40da-bbda-b39741357a36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Choose an optionLargeMediumSmall</value>
      <webElementGuid>bc43db73-0edb-4fa1-8458-15a325f2a3ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pa_size&quot;)</value>
      <webElementGuid>823619a6-011f-4e2e-b255-7f50ba1ffda8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>02138adc-cdc6-46c1-b1a4-419a939c98c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pa_size</value>
      <webElementGuid>2a4401f6-1875-447b-be53-e654820d7400</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>attribute_pa_size</value>
      <webElementGuid>ed7a1d3f-aaa7-4602-b37c-443643fa912c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-attribute_name</name>
      <type>Main</type>
      <value>attribute_pa_size</value>
      <webElementGuid>733b1edf-10c1-40b8-95b6-1d64e6f30204</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-show_option_none</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>6ef60783-0dba-4a0b-91dd-9576f8cadb8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Choose an optionLargeMediumSmall</value>
      <webElementGuid>48206e8e-a3de-4903-a0b9-cb9bf83c6347</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pa_size&quot;)</value>
      <webElementGuid>aa4a173a-52ea-45c7-b09f-9c932748ab02</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='pa_size']</value>
      <webElementGuid>ee2c2cc7-b666-4168-bee3-59fbec455787</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-1162']/div/div[2]/form/table/tbody/tr[2]/td/select</value>
      <webElementGuid>0c2bd961-7083-4b44-8240-35ff331ece0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Size'])[1]/following::select[1]</value>
      <webElementGuid>d805af35-949b-4e65-ac1a-d649492c8ade</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Color'])[1]/following::select[2]</value>
      <webElementGuid>c80c66de-28a7-48e9-ae2c-17b37953d265</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QTY'])[1]/preceding::select[1]</value>
      <webElementGuid>2b4c52e9-54b5-473e-98c0-0ba460cc1de0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to cart'])[1]/preceding::select[1]</value>
      <webElementGuid>b232100b-beab-42aa-a19b-62c643c3aff9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/select</value>
      <webElementGuid>966f3cb2-1e41-42e7-aa17-0078179c5202</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'pa_size' and @name = 'attribute_pa_size' and (text() = 'Choose an optionLargeMediumSmall' or . = 'Choose an optionLargeMediumSmall')]</value>
      <webElementGuid>8053bedc-4942-4a18-936c-e676bf27e4f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
